// console.clear();
// console.log('test work');
// // console.clear();
// console.warn("last warning");
// console.error("last warning");
let Name = "dheeraj sahani";
console.log("data type of : " + (typeof Name));
let num = 346.23;
console.log("data type of : " + (typeof num));
let bool = false;
console.log("data type of : " + (typeof bool));
let null1 = null;
console.log("data type of : " + (typeof null1));
let undefined1 = undefined;
console.log("data type of : " + (typeof undefined1));
let marks = [2,43,52,12,4,"jfjl",false];
console.log(typeof marks);